stilab-ets/stilab-ets.github.io

README.md
tests/awards/AwardsPage.spec.ts
tests/events/EventCard.spec.ts
tests/events/EventsPage.spec.ts
tests/layout/Footer.spec.ts
tests/layout/Header.spec.ts
tests/people/PeoplePage.spec.ts
tests/projects/ProjectPage.spec.ts
tests/publications/PublicationsPage.spec.ts
tests/research/ResearchPage.spec.ts
tests/teaching/CourseCard.spec.ts
tests/teaching/TeachingPage.spec.ts
tests/vacancies/VacanciesInfoBanner.spec.ts
tests/vacancies/VacanciesPage.spec.ts
tests/vacancies/VacancyCard.spec.ts
vite.config.mts

Added UI Unit tests
Current coverage :    

TEST : Added UI Unit tests

---

doc/global/database.puml

[DOC]: Added database Schema

---

src/test/auth/LoginForm.spec.ts
src/test/auth/RegisterForm.spec.ts
src/test/forms/EventForm.spec.ts
src/test/forms/ProjectForm.spec.ts
src/test/forms/PublicationForm.spec.ts

[TEST] : Add forms tests

---

src/components/forms/PublicationForm.vue
src/components/publications/PublicationCard.vue
src/data/translations/publications.translate.ts
src/test/forms/AdminManagementForm.spec.ts
src/test/forms/AwardForm.spec.ts
src/test/forms/MemberForm.spec.ts
src/test/forms/ResearchForm.spec.ts
src/test/forms/TeachingForm.spec.ts
src/test/forms/UserSettingsForm.spec.ts
src/test/forms/VacancyForm.spec.ts

- Add forms tests
- Add copy bibtex button
- Add bibtex autocomplete
Test coverage :
Bibtext copy :
Bibtex autocomplete:

Form unit tests and more

---

backend/backend/serializers/publication_serializer.py
backend/backend/views/publication_views.py
src/components/forms/PublicationForm.vue
src/test/forms/PublicationForm.spec.ts

Implemented POST /api/publications and calling the endpoint in PublicationForm.vue
POST /api/publications
Validate duplicated publications
Create publication with the form:
For now, the frontend is calling the endpoint from localhost. We will need to change the host when we deploy on render.
To test the endpoint, use this url http://localhost:8000/api/publications/
and this payload : 
{
"id": "smith2023",
"entrytype": "article",
"citekey": "Smith2023",
"title": "Some Research Paper",
"author": "John Smith and Jane Doe",
"journal": "Journal of Examples",
"year": 2023,
"volume": "12",
"number": "3",
"pages": "123-130",
"url": "https://example.com/paper",
"is_approved": false
}

Feat post api publications

---

backend/backend/test/test_member.py
backend/backend/views/member_view.py
backend/config/urls.py
doc/programmerGuide/programmerGuide.md
src/components/auth/RegisterForm.vue
src/components/people/PeopleFilters.vue
src/components/people/PeoplePage.vue
src/components/people/PersonCard.vue
src/components/people/PersonModal.vue
src/data/translations/auth.translate.ts
src/data/translations/person.translate.ts
src/test/people/PeopleFilters.spec.ts
src/test/people/PeoplePage.spec.ts

- Display members data to frontend. 
- New endpoint GET /api/members is created
Test user with links:

Display members data

---

backend/backend/serializers/award_recipient_serializer.py
backend/backend/serializers/award_serializer.py
backend/backend/test/test_awards.py
backend/backend/views/awards_view.py
backend/backend/views/member_view.py
backend/config/urls.py

Added the awards view to get all awards. Also added tests. Fixed issues i was getting when running tests due to imports.

Adding api and tests for awards view

---

backend/backend/views/publication_views.py

This PR adds PUT and DELETE endpoints for the Publication model.

add PUT and DELETE endpoints for publications

---

backend/backend/admin/__init__.py
backend/backend/admin/course_admin.py

Adding course management in the admin dashboard

Adding course management in the admin dashboard

---

backend/backend/serializers/member_serializer.py
backend/backend/test/test_member.py
backend/backend/views/member_view.py
backend/config/urls.py

Added POST to members for the admin

---

backend/backend/serializers/member_serializer.py
backend/backend/test/test_member.py
backend/backend/views/member_view.py

An admin can now update a member with PUT /api/members

Added PUT to members for the admins

---

src/components/publications/PublicationCard.vue
src/services/MainAPI.ts

Adjust publication page
- Displayed all the informations
- Bibtex button will now show the bibtex
- Adjust publication interface
Before : 
After : 

[FIX] : Adjust publication page

---

src/services/MainAPI.ts

Update researches endpoint call on UI
Researches are now displayed correctly : 

[FIX]: Update researches endpoint call on UI

---

src/components/home/Hero.vue
src/components/home/StatsSection.vue
src/components/layout/footer/LabInfo.vue
src/hooks/layout/useFooterData.ts

display real data on homepage   
updated footer information

[FEAT]:Display real data on Homepage

---

src/App.vue
src/components/admin/AdminInvitationManagement.vue
src/components/admin/InvitationSender.vue
src/components/admin/invitation/BulkInvitationForm.vue
src/components/admin/invitation/InvitationHistorySection.vue
src/components/admin/invitation/InvitationNavigationTabs.vue
src/components/admin/invitation/InvitationStatsSection.vue
src/components/admin/invitation/SingleInvitationForm.vue
src/components/auth/LoginForm.vue
src/components/auth/LoginPage.vue
src/components/auth/RegisterForm.vue
src/components/auth/register/LinksSection.vue
src/components/auth/register/PersonalInfoSection.vue
src/components/auth/register/ProfessionalInfoSection.vue
src/components/auth/register/RegistrationActions.vue
src/components/auth/register/SecuritySection.vue
src/components/dashboard/DashboardPage.vue
src/composables/useInvitationToken.ts
src/composables/useRouteGuard.ts
src/data/translations/adminInvitationManagement.translate.ts
src/data/translations/index.ts
src/data/translations/invitations.translate.ts
src/hooks/auth/useAuth.ts
src/hooks/auth/useRegister.ts
src/hooks/invitations/useInvitationManagement.ts
src/hooks/layout/useNavigation.ts
src/main.ts
src/test/auth/RegisterForm.spec.ts

Added Route granular protection
Register with token
Admin Invitation management
Invitation management
Mock endpoints (needs to be implemented in backend)
```shell
POST /api/validate-invitation-token {email: string, token: string} -> bool valid
POST /api/send-mail-invitation {email: string} -> bool success
GET /api/invitations -> {email, role, sentAt, status (pending, expired, registered, canceled), expiresAt}
PUT /api/invitation/{id}
DELETE /api/invitations/{id}
```
Please include a summary of the changes and the related issue. Include any relevant context or motivation for the changes.
```typescript
const routeProtections: Record<string, RouteProtection> = {
'home': { requiresAuth: false },
'people': { requiresAuth: false }, …
```

Middleware refactor

---

src/App.vue
src/components/dashboard/admin/AdminDashboard.vue
src/components/dashboard/admin/AdminForm.vue
src/components/people/MemberForm.vue
src/data/translations/dashboard.translate.ts
src/hooks/dashboard/useAdminDashboard.ts
src/test/admin/AdminForm.spec.ts
src/test/forms/MemberForm.spec.ts

Add member form
Also added a tab in the admin dashboard that shows all the available forms :

Feat add member form

---

src/App.vue
src/components/dashboard/admin/AdminForm.vue
src/components/research/ResearchForm.vue
src/test/admin/AdminForm.spec.ts
src/test/forms/ResearchForm.spec.ts

Feat add research form

---

src/test/admin/AdminDashboard.spec.ts
src/test/auth/LoginPage.spec.ts
src/test/auth/RegisterForm.spec.ts
src/test/dashboard/ProfessorDashboard.spec.ts
src/test/dashboard/StudentDashboard.spec.ts

Added dashboards tests
New coverage

[TEST]: Added dashboards tests

---

doc/global/database.puml
doc/usecase/usecase.puml

Updated use case diagram and DB Schema
Use cases (added cu08 and cu09)
DB (added courses entity)

[DOC]: Updated use case diagram and DB Schema

---

doc/usecase/usecase.puml

[DOC]: Updated use case diagram
